import { test, expect } from '@playwright/test';

test('add new geofence zone', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Human Resources Management').click();
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Master data').click();
  await page.getByRole('complementary').getByTestId('Geofence').click();
  await page.locator('.ps-menuitem-root.ps-submenu-root.ps-open.css-1ulgp3w > .ps-submenu-content > .css-ewdv3l > .ps-menuitem-root > .ps-menu-button').click();
  await page.getByText('Geofence ZoneSelect a geofence zoneFill the details below to add a new geofence').click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('Head Office Zone');
  await page.locator('div:nth-child(5) > .mb-3 > .border > .css-b62m3t-container > .react-select__control > .react-select__value-container > .react-select__input-container').click();
  await page.getByRole('option', { name: 'Nugegoda' }).click();
  await page.getByText('Circle (center point + radius)').click();
  await page.getByRole('option', { name: 'Circle (center point + radius)' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('Colombo Head Office');
  await page.getByRole('button', { name: 'Search location' }).click();
  await page.getByRole('button', { name: 'Search location' }).click();
  await page.getByRole('button', { name: 'Show manual entry' }).click();
  await page.getByRole('button', { name: 'Hide manual entry' }).click();
  await page.getByRole('button', { name: 'Search location' }).click();
  await page.getByRole('button', { name: 'Show manual entry' }).click();
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('79.861244');
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().fill('');
  await page.locator('div').filter({ hasText: /^\+−Draw a circleEdit layersDelete layers Leaflet \| © OpenStreetMap contributors$/ }).nth(1).click();
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().fill('6.927079');
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).fill('200');
  await page.getByRole('button', { name: 'Center map here' }).click();
  await page.locator('.leaflet-interactive').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Please fill the required').click();
  //the test fails because the required fields are not filled. The test should be updated to fill all required fields before clicking the save button.
});