import { test, expect } from '@playwright/test';

test('add eb exam type', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Human Resources Management').click();
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Master data').click();
  await page.getByRole('complementary').getByTestId('Eb exam type').click();
  await page.getByTestId('add new').nth(3).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().press('ControlOrMeta+c');
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('Practical Examination');
  await page.getByText('Select a employee category').click();
  await page.getByRole('option', { name: 'EMPC0011 - Sift- Time Employee' }).click();
  await page.getByText('Select a grade').click();
  await page.getByRole('option', { name: 'Grade II', exact: true }).click();
  await page.locator('textarea').click();
  await page.locator('textarea').fill('Examination used to assess practical skills.');
  await page.getByRole('button', { name: 'Add new' }).first().click();
  await page.locator('.react-select__input-container.css-1ezlvm0').click();
  await page.getByRole('option', { name: 'DES0002 - Administration' }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Add new' }).nth(1).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Promotion');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
});

test('update eb exam type', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Human Resources Management').click();
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Master data').click();
  await page.getByRole('complementary').getByTestId('Eb exam type').click();
  await page.getByTestId('add new').nth(3).click();
  await page.getByText('Select a eb exam type').click();
  await page.getByRole('option', { name: 'EBEXTY0001 - Network' }).click();
  await page.getByRole('button', { name: 'Add new' }).first().click();
  await page.locator('.react-select__input-container.css-1ezlvm0').click();
  await page.getByRole('option', { name: 'DES0002 - Administration' }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button').nth(1).click();
  await page.locator('.col-md-12 > .mb-3 > .border > .css-b62m3t-container > .react-select__control > .react-select__indicators > .react-select__indicator.react-select__clear-indicator > .css-8mmkcg').click();
  await page.locator('.react-select__input-container.css-1ezlvm0').click();
  await page.getByRole('option', { name: 'DES0007 - HR Executive' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
});

test('delete eb exam type', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Human Resources Management').click();
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Master data').click();
  await page.getByRole('complementary').getByTestId('Eb exam type').click();
  await page.getByTestId('add new').nth(3).click();
  await page.getByText('Select a eb exam type').click();
  await page.getByRole('option', { name: 'EBEXTY0004 - Network' }).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'Yes, remove it!' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});

test('list view eb exam type', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Human Resources Management').click();
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Master data').click();
  await page.getByRole('complementary').getByTestId('Eb exam type').click();
  await page.getByTestId('list view').nth(3).click();
  await page.getByRole('row', { name: '1 EBEXTY0001 Network' }).getByRole('img').click();
});

test('change privileges', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Administration').click();
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Privileges').click();
  await page.getByRole('link', { name: 'User privileges' }).click();
  await page.locator('.react-select__input-container.css-1ezlvm0').click();
  await page.getByRole('option', { name: 'erp@test' }).click();
  await page.getByText('Select a module').click();
  await page.getByRole('option', { name: 'human resource' }).click();
  await page.locator('[id="68"]').uncheck();
  await page.locator('[id="69"]').uncheck();
  await page.locator('[id="70"]').uncheck();
  await page.getByRole('button', { name: 'Save' }).click();
});

test('add eb exam type without permission', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Human Resources Management').click();
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Master data').click();
  await page.getByRole('complementary').getByTestId('Eb exam type').click();
  await page.getByTestId('add new').nth(3).click();
  await page.getByRole('textbox').first().fill('Practical Examination Without Permission');
  await page.getByText('Select a employee category').click();
  await page.getByRole('option', { name: 'EMPC0011 - Sift- Time Employee' }).click();
  await page.getByText('Select a grade').click();
  await page.getByRole('option', { name: 'Grade II', exact: true }).click();
  await page.locator('textarea').fill('Permission validation test.');
  await page.getByRole('button', { name: 'Add new' }).first().click();
  await page.locator('.react-select__input-container.css-1ezlvm0').click();
  await page.getByRole('option', { name: 'DES0002 - Administration' }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Add new' }).nth(1).click();
  await page.getByRole('textbox').nth(2).fill('Promotion');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  
});


test('update eb exam type without permission', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('');
  await page.locator('input[type="text"]').press('CapsLock');
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Human Resources Management').click();
  await page.getByTestId('legend-location-button').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Master data').click();
  await page.getByRole('complementary').getByTestId('Eb exam type').click();
  await page.getByTestId('add new').nth(5).click();
  await page.getByText('Select a eb exam type').click();
  await page.getByRole('option', { name: 'EBEXTY0001 - Network' }).click();
  await page.getByText('Select a employee category').click();
  await page.getByRole('option', { name: 'EMPC0007 - Full-Time Employees' }).click();
  await page.getByText('Grade III').click();
  await page.getByRole('option', { name: 'Grade I', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
});

test('delete eb exam type without permission', async ({ page }) => {
  await page.goto('http://124.43.17.171:4001/');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('input[type="text"]').fill('erp@test');
  await page.locator('input[type="password"]').fill('dev@erp@test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Explore ERP Features' }).click();
  await page.getByText('Human Resources Management').click();
  await page.getByTestId('legend-location-button').click();
  await page.getByRole('option', { name: '- Nugegoda' }).click();
  await page.getByRole('complementary').getByTestId('Master data').click();
  await page.getByRole('complementary').getByTestId('Eb exam type').click();
  await page.getByTestId('add new').nth(5).click();
  await page.getByText('Select a eb exam type').click();
  await page.getByRole('option', { name: 'EBEXTY0004 - Network' }).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'Yes, remove it!' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});

